/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        canvas: '#000000',
        surface: {
          card: '#0a0a0c',
          elevated: '#101012',
          deep: '#06060a',
          light: '#f1f7fe',
        },
        primary: {
          DEFAULT: '#fcfdff',
          on: '#000000',
        },
        hairline: {
          DEFAULT: 'rgba(255, 255, 255, 0.06)',
          strong: 'rgba(255, 255, 255, 0.14)',
        },
        divider: {
          soft: 'rgba(255, 255, 255, 0.04)',
        },
        ink: '#fcfdff',
        body: 'rgba(252, 253, 255, 0.86)',
        charcoal: 'rgba(252, 253, 255, 0.7)',
        mute: '#a1a4a5',
        ash: '#888e90',
        stone: '#464a4d',
        'on-light': {
          DEFAULT: '#000000',
          mute: 'rgba(0, 0, 51, 0.7)',
        },
        accent: {
          orange: '#ff801f',
          'orange-glow': 'rgba(255, 89, 0, 0.22)',
          yellow: '#ffc53d',
          blue: '#3b9eff',
          'blue-glow': 'rgba(0, 117, 255, 0.34)',
          green: '#11ff99',
          'green-glow': 'rgba(34, 255, 153, 0.18)',
          red: '#ff2047',
          'red-glow': 'rgba(255, 32, 71, 0.34)',
        },
        link: '#3b9eff',
      },
      fontFamily: {
        display: ['"Playfair Display"', 'serif'],
        sans: ['"Inter Tight"', 'sans-serif'],
        ui: ['Inter', 'sans-serif'],
        mono: ['"Geist Mono"', 'monospace'],
      },
      fontSize: {
        'display-xxl': ['96px', { lineHeight: '1', letterSpacing: '-0.96px' }],
        'display-xl': ['76.8px', { lineHeight: '1', letterSpacing: '-0.768px' }],
        'display-lg': ['56px', { lineHeight: '1.2', letterSpacing: '-2.8px' }],
        'heading-md': ['24px', { lineHeight: '1.5', letterSpacing: '-0.4px', fontWeight: '500' }],
        'heading-sm': ['20px', { lineHeight: '1.3', letterSpacing: '-0.3px', fontWeight: '500' }],
        'subtitle': ['20px', { lineHeight: '1.3', letterSpacing: '0', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '-0.8px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.43', letterSpacing: '0', fontWeight: '400' }],
        'button-md': ['14px', { lineHeight: '1.43', letterSpacing: '0', fontWeight: '500' }],
        'button-sm': ['14px', { lineHeight: '1.43', letterSpacing: '0.35px', fontWeight: '500' }],
        'caption': ['12px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'caption-emph': ['14px', { lineHeight: '1.0', letterSpacing: '0', fontWeight: '600' }],
        'code-md': ['13px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
      },
      spacing: {
        'xxs': '2px',
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '24px',
        'xxl': '32px',
        'xxxl': '48px',
        'section': '96px',
        'band': '128px',
      },
      borderRadius: {
        'none': '0px',
        'xs': '4px',
        'sm': '6px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        'full': '9999px',
      },
      boxShadow: {
        'none': 'none',
      },
      keyframes: {
        slideUpAndFade: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'slide-up': 'slideUpAndFade 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
    },
  },
  plugins: [],
}
